package com.persistance.model;
// Generated 30 déc. 2018 16:29:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name="card"
    ,catalog="logmein"
)
public class Card  implements java.io.Serializable {


     private int idCard;
     private String color;
     private String face;
     private int value;
     private Set<DeckCard> deckCards = new HashSet<DeckCard>(0);
     private Set<UserCard> userCards = new HashSet<UserCard>(0);

    public Card() {
    }

	
    public Card(int idCard, String color, String face, int value) {
        this.idCard = idCard;
        this.color = color;
        this.face = face;
        this.value = value;
    }
    public Card(int idCard, String color, String face, int value, Set<DeckCard> deckCards, Set<UserCard> userCards) {
       this.idCard = idCard;
       this.color = color;
       this.face = face;
       this.value = value;
       this.deckCards = deckCards;
       this.userCards = userCards;
    }
   
     @Id 

    
    @Column(name="id_card", unique=true, nullable=false)
    public int getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(int idCard) {
        this.idCard = idCard;
    }

    
    @Column(name="color", nullable=false, length=100)
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }

    
    @Column(name="face", nullable=false, length=100)
    public String getFace() {
        return this.face;
    }
    
    public void setFace(String face) {
        this.face = face;
    }

    
    @Column(name="value", nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="card")
    public Set<DeckCard> getDeckCards() {
        return this.deckCards;
    }
    
    public void setDeckCards(Set<DeckCard> deckCards) {
        this.deckCards = deckCards;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="card")
    public Set<UserCard> getUserCards() {
        return this.userCards;
    }
    
    public void setUserCards(Set<UserCard> userCards) {
        this.userCards = userCards;
    }


    


}


