package com.persistance.model;
// Generated 30 déc. 2018 16:29:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Deck generated by hbm2java
 */
@Entity
@Table(name="deck"
    ,catalog="logmein"
)
public class Deck  implements java.io.Serializable {


     private Integer idDeck;
     private String nameDeck;
     private Set<GameDeck> gameDecks = new HashSet<GameDeck>(0);
     private Set<DeckCard> deckCards = new HashSet<DeckCard>(0);

    public Deck() {
    }

    public Deck(String nameDeck, Set<GameDeck> gameDecks, Set<DeckCard> deckCards) {
       this.nameDeck = nameDeck;
       this.gameDecks = gameDecks;
       this.deckCards = deckCards;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_deck", unique=true, nullable=false)
    public Integer getIdDeck() {
        return this.idDeck;
    }
    
    public void setIdDeck(Integer idDeck) {
        this.idDeck = idDeck;
    }

    
    @Column(name="name_deck", length=100)
    public String getNameDeck() {
        return this.nameDeck;
    }
    
    public void setNameDeck(String nameDeck) {
        this.nameDeck = nameDeck;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="deck")
    public Set<GameDeck> getGameDecks() {
        return this.gameDecks;
    }
    
    public void setGameDecks(Set<GameDeck> gameDecks) {
        this.gameDecks = gameDecks;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="deck")
    public Set<DeckCard> getDeckCards() {
        return this.deckCards;
    }
    
    public void setDeckCards(Set<DeckCard> deckCards) {
        this.deckCards = deckCards;
    }




}


