package com.persistance.model;
// Generated 30 déc. 2018 16:29:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GameDeck generated by hbm2java
 */
@Entity
@Table(name="game_deck"
    ,catalog="logmein"
)
public class GameDeck  implements java.io.Serializable {


     private Integer idGameDeck;
     private Deck deck;
     private Game game;

    public GameDeck() {
    }

    public GameDeck(Deck deck, Game game) {
       this.deck = deck;
       this.game = game;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_game_deck", unique=true, nullable=false)
    public Integer getIdGameDeck() {
        return this.idGameDeck;
    }
    
    public void setIdGameDeck(Integer idGameDeck) {
        this.idGameDeck = idGameDeck;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_deck", nullable=false)
    public Deck getDeck() {
        return this.deck;
    }
    
    public void setDeck(Deck deck) {
        this.deck = deck;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_game", nullable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }




}


