package com.persistance.model;
// Generated 30 déc. 2018 16:29:22 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GameUser generated by hbm2java
 */
@Entity
@Table(name="game_user"
    ,catalog="logmein"
)
public class GameUser  implements java.io.Serializable {


     private Integer idGameUser;
     private Game game;
     private User user;

    public GameUser() {
    }

    public GameUser(Game game, User user) {
       this.game = game;
       this.user = user;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_game_user", unique=true, nullable=false)
    public Integer getIdGameUser() {
        return this.idGameUser;
    }
    
    public void setIdGameUser(Integer idGameUser) {
        this.idGameUser = idGameUser;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_game", nullable=false)
    public Game getGame() {
        return this.game;
    }
    
    public void setGame(Game game) {
        this.game = game;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id_user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


