package com.persistance.model;
// Generated 30 déc. 2018 16:29:22 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name="game"
    ,catalog="logmein"
)
public class Game  implements java.io.Serializable {


     private Integer idGame;
     private String nameGame;
     private Set<GameDeck> gameDecks = new HashSet<GameDeck>(0);
     private Set<GameUser> gameUsers = new HashSet<GameUser>(0);

    public Game() {
    }

    public Game(String nameGame, Set<GameDeck> gameDecks, Set<GameUser> gameUsers) {
       this.nameGame = nameGame;
       this.gameDecks = gameDecks;
       this.gameUsers = gameUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_game", unique=true, nullable=false)
    public Integer getIdGame() {
        return this.idGame;
    }
    
    public void setIdGame(Integer idGame) {
        this.idGame = idGame;
    }

    
    @Column(name="name_game", length=100)
    public String getNameGame() {
        return this.nameGame;
    }
    
    public void setNameGame(String nameGame) {
        this.nameGame = nameGame;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="game")
    public Set<GameDeck> getGameDecks() {
        return this.gameDecks;
    }
    
    public void setGameDecks(Set<GameDeck> gameDecks) {
        this.gameDecks = gameDecks;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="game" )// cascade = CascadeType.ALL
    public Set<GameUser> getGameUsers() {
        return this.gameUsers;
    }
    
    public void setGameUsers(Set<GameUser> gameUsers) {
        this.gameUsers = gameUsers;
    }




}


